name: mtdev_planificador_comidas
description: >
  MTDev Planificador-comidas is an application for meal planning and shopping lists.
  Designed as a portfolio project by Marta Torre.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies for your project
  cupertino_icons: ^1.0.8
  provider: any
  shared_preferences: any
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Section for assets
  assets:
    - assets/images/

  # Custom fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

# Additional metadata
homepage: https://github.com/martatorredev/mtdev-planificador-comidas
author: Marta Torre <hola@martatorre.dev>
license: GPL-3.0
